// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Weasel.proto

package com.softwaremill.weasel9000;

public final class Weasel {
  private Weasel() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code com.softwaremill.weasel9000.VOTE_TYPE}
   */
  public enum VOTE_TYPE
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>LIKE = 1;</code>
     */
    LIKE(0, 1),
    /**
     * <code>DISLIKE = 2;</code>
     */
    DISLIKE(1, 2),
    ;

    /**
     * <code>LIKE = 1;</code>
     */
    public static final int LIKE_VALUE = 1;
    /**
     * <code>DISLIKE = 2;</code>
     */
    public static final int DISLIKE_VALUE = 2;


    public final int getNumber() { return value; }

    public static VOTE_TYPE valueOf(int value) {
      switch (value) {
        case 1: return LIKE;
        case 2: return DISLIKE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<VOTE_TYPE>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<VOTE_TYPE>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<VOTE_TYPE>() {
            public VOTE_TYPE findValueByNumber(int number) {
              return VOTE_TYPE.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.softwaremill.weasel9000.Weasel.getDescriptor().getEnumTypes().get(0);
    }

    private static final VOTE_TYPE[] VALUES = values();

    public static VOTE_TYPE valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private VOTE_TYPE(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.softwaremill.weasel9000.VOTE_TYPE)
  }

  public interface VoteOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required int32 room_id = 1;
    /**
     * <code>required int32 room_id = 1;</code>
     */
    boolean hasRoomId();
    /**
     * <code>required int32 room_id = 1;</code>
     */
    int getRoomId();

    // required .com.softwaremill.weasel9000.VOTE_TYPE vote = 2;
    /**
     * <code>required .com.softwaremill.weasel9000.VOTE_TYPE vote = 2;</code>
     */
    boolean hasVote();
    /**
     * <code>required .com.softwaremill.weasel9000.VOTE_TYPE vote = 2;</code>
     */
    com.softwaremill.weasel9000.Weasel.VOTE_TYPE getVote();

    // required int64 timestamp = 3;
    /**
     * <code>required int64 timestamp = 3;</code>
     */
    boolean hasTimestamp();
    /**
     * <code>required int64 timestamp = 3;</code>
     */
    long getTimestamp();
  }
  /**
   * Protobuf type {@code com.softwaremill.weasel9000.Vote}
   */
  public static final class Vote extends
      com.google.protobuf.GeneratedMessage
      implements VoteOrBuilder {
    // Use Vote.newBuilder() to construct.
    private Vote(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Vote(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Vote defaultInstance;
    public static Vote getDefaultInstance() {
      return defaultInstance;
    }

    public Vote getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Vote(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              roomId_ = input.readInt32();
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              com.softwaremill.weasel9000.Weasel.VOTE_TYPE value = com.softwaremill.weasel9000.Weasel.VOTE_TYPE.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                vote_ = value;
              }
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              timestamp_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.softwaremill.weasel9000.Weasel.internal_static_com_softwaremill_weasel9000_Vote_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.softwaremill.weasel9000.Weasel.internal_static_com_softwaremill_weasel9000_Vote_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.softwaremill.weasel9000.Weasel.Vote.class, com.softwaremill.weasel9000.Weasel.Vote.Builder.class);
    }

    public static com.google.protobuf.Parser<Vote> PARSER =
        new com.google.protobuf.AbstractParser<Vote>() {
      public Vote parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Vote(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Vote> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required int32 room_id = 1;
    public static final int ROOM_ID_FIELD_NUMBER = 1;
    private int roomId_;
    /**
     * <code>required int32 room_id = 1;</code>
     */
    public boolean hasRoomId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 room_id = 1;</code>
     */
    public int getRoomId() {
      return roomId_;
    }

    // required .com.softwaremill.weasel9000.VOTE_TYPE vote = 2;
    public static final int VOTE_FIELD_NUMBER = 2;
    private com.softwaremill.weasel9000.Weasel.VOTE_TYPE vote_;
    /**
     * <code>required .com.softwaremill.weasel9000.VOTE_TYPE vote = 2;</code>
     */
    public boolean hasVote() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required .com.softwaremill.weasel9000.VOTE_TYPE vote = 2;</code>
     */
    public com.softwaremill.weasel9000.Weasel.VOTE_TYPE getVote() {
      return vote_;
    }

    // required int64 timestamp = 3;
    public static final int TIMESTAMP_FIELD_NUMBER = 3;
    private long timestamp_;
    /**
     * <code>required int64 timestamp = 3;</code>
     */
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int64 timestamp = 3;</code>
     */
    public long getTimestamp() {
      return timestamp_;
    }

    private void initFields() {
      roomId_ = 0;
      vote_ = com.softwaremill.weasel9000.Weasel.VOTE_TYPE.LIKE;
      timestamp_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasRoomId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasVote()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTimestamp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, roomId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, vote_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt64(3, timestamp_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, roomId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, vote_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, timestamp_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.softwaremill.weasel9000.Weasel.Vote parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.softwaremill.weasel9000.Weasel.Vote parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.softwaremill.weasel9000.Weasel.Vote parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.softwaremill.weasel9000.Weasel.Vote parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.softwaremill.weasel9000.Weasel.Vote parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.softwaremill.weasel9000.Weasel.Vote parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.softwaremill.weasel9000.Weasel.Vote parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.softwaremill.weasel9000.Weasel.Vote parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.softwaremill.weasel9000.Weasel.Vote parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.softwaremill.weasel9000.Weasel.Vote parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.softwaremill.weasel9000.Weasel.Vote prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.softwaremill.weasel9000.Vote}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.softwaremill.weasel9000.Weasel.VoteOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.softwaremill.weasel9000.Weasel.internal_static_com_softwaremill_weasel9000_Vote_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.softwaremill.weasel9000.Weasel.internal_static_com_softwaremill_weasel9000_Vote_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.softwaremill.weasel9000.Weasel.Vote.class, com.softwaremill.weasel9000.Weasel.Vote.Builder.class);
      }

      // Construct using com.softwaremill.weasel9000.Weasel.Vote.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        roomId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        vote_ = com.softwaremill.weasel9000.Weasel.VOTE_TYPE.LIKE;
        bitField0_ = (bitField0_ & ~0x00000002);
        timestamp_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.softwaremill.weasel9000.Weasel.internal_static_com_softwaremill_weasel9000_Vote_descriptor;
      }

      public com.softwaremill.weasel9000.Weasel.Vote getDefaultInstanceForType() {
        return com.softwaremill.weasel9000.Weasel.Vote.getDefaultInstance();
      }

      public com.softwaremill.weasel9000.Weasel.Vote build() {
        com.softwaremill.weasel9000.Weasel.Vote result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.softwaremill.weasel9000.Weasel.Vote buildPartial() {
        com.softwaremill.weasel9000.Weasel.Vote result = new com.softwaremill.weasel9000.Weasel.Vote(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.roomId_ = roomId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.vote_ = vote_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.timestamp_ = timestamp_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.softwaremill.weasel9000.Weasel.Vote) {
          return mergeFrom((com.softwaremill.weasel9000.Weasel.Vote)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.softwaremill.weasel9000.Weasel.Vote other) {
        if (other == com.softwaremill.weasel9000.Weasel.Vote.getDefaultInstance()) return this;
        if (other.hasRoomId()) {
          setRoomId(other.getRoomId());
        }
        if (other.hasVote()) {
          setVote(other.getVote());
        }
        if (other.hasTimestamp()) {
          setTimestamp(other.getTimestamp());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasRoomId()) {
          
          return false;
        }
        if (!hasVote()) {
          
          return false;
        }
        if (!hasTimestamp()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.softwaremill.weasel9000.Weasel.Vote parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.softwaremill.weasel9000.Weasel.Vote) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required int32 room_id = 1;
      private int roomId_ ;
      /**
       * <code>required int32 room_id = 1;</code>
       */
      public boolean hasRoomId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 room_id = 1;</code>
       */
      public int getRoomId() {
        return roomId_;
      }
      /**
       * <code>required int32 room_id = 1;</code>
       */
      public Builder setRoomId(int value) {
        bitField0_ |= 0x00000001;
        roomId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 room_id = 1;</code>
       */
      public Builder clearRoomId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        roomId_ = 0;
        onChanged();
        return this;
      }

      // required .com.softwaremill.weasel9000.VOTE_TYPE vote = 2;
      private com.softwaremill.weasel9000.Weasel.VOTE_TYPE vote_ = com.softwaremill.weasel9000.Weasel.VOTE_TYPE.LIKE;
      /**
       * <code>required .com.softwaremill.weasel9000.VOTE_TYPE vote = 2;</code>
       */
      public boolean hasVote() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required .com.softwaremill.weasel9000.VOTE_TYPE vote = 2;</code>
       */
      public com.softwaremill.weasel9000.Weasel.VOTE_TYPE getVote() {
        return vote_;
      }
      /**
       * <code>required .com.softwaremill.weasel9000.VOTE_TYPE vote = 2;</code>
       */
      public Builder setVote(com.softwaremill.weasel9000.Weasel.VOTE_TYPE value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        vote_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .com.softwaremill.weasel9000.VOTE_TYPE vote = 2;</code>
       */
      public Builder clearVote() {
        bitField0_ = (bitField0_ & ~0x00000002);
        vote_ = com.softwaremill.weasel9000.Weasel.VOTE_TYPE.LIKE;
        onChanged();
        return this;
      }

      // required int64 timestamp = 3;
      private long timestamp_ ;
      /**
       * <code>required int64 timestamp = 3;</code>
       */
      public boolean hasTimestamp() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int64 timestamp = 3;</code>
       */
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>required int64 timestamp = 3;</code>
       */
      public Builder setTimestamp(long value) {
        bitField0_ |= 0x00000004;
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 timestamp = 3;</code>
       */
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000004);
        timestamp_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.softwaremill.weasel9000.Vote)
    }

    static {
      defaultInstance = new Vote(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.softwaremill.weasel9000.Vote)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_softwaremill_weasel9000_Vote_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_softwaremill_weasel9000_Vote_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014Weasel.proto\022\033com.softwaremill.weasel9" +
      "000\"`\n\004Vote\022\017\n\007room_id\030\001 \002(\005\0224\n\004vote\030\002 \002" +
      "(\0162&.com.softwaremill.weasel9000.VOTE_TY" +
      "PE\022\021\n\ttimestamp\030\003 \002(\003*\"\n\tVOTE_TYPE\022\010\n\004LI" +
      "KE\020\001\022\013\n\007DISLIKE\020\002"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_softwaremill_weasel9000_Vote_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_softwaremill_weasel9000_Vote_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_softwaremill_weasel9000_Vote_descriptor,
              new java.lang.String[] { "RoomId", "Vote", "Timestamp", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
